function school_import = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  AMLR03120DILATIONSCHOOLSREGION = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  AMLR03120DILATIONSCHOOLSREGION = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  AMLR03120dilationschoolsregion = importfile("C:\Github\AMLR23-24_acoustics\data\AMLR03\120kHz\AMLR03_120_dilation_schools_region.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Mar-2025 14:05:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 44, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Region_ID", "Region_name", "Region_class", "Process_ID", "Sv_mean", "Sv_max", "Height_mean", "Depth_mean", "Ping_M", "Dist_M", "Date_S", "Time_S", "Date_E", "Time_E", "Date_M", "Time_M", "Lat_S", "Lon_S", "Lat_E", "Lon_E", "Lat_M", "Lon_M", "Program_version", "EV_filename", "Uncorrected_length", "Uncorrected_thickness", "Uncorrected_perimeter", "Uncorrected_area", "Standard_deviation", "Corrected_length", "Corrected_thickness", "Corrected_perimeter", "Corrected_area", "Horizontal_roughness_coefficient", "Vertical_roughness_coefficient", "ABC", "Area_Backscatter_Strength", "Thickness_mean", "Frequency", "Center_of_mass", "Inertia", "Proportion_occupied", "Equivalent_area", "Aggregation_index"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "datetime", "datetime", "datetime", "datetime", "datetime", "datetime", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Program_version", "EV_filename"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date_S", "InputFormat", "yyyyMMdd");
opts = setvaropts(opts, "Time_S", "InputFormat", "HH:mm:ss.SSSS");
opts = setvaropts(opts, "Date_E", "InputFormat", "yyyyMMdd");
opts = setvaropts(opts, "Time_E", "InputFormat", "HH:mm:ss.SSSS");
opts = setvaropts(opts, "Date_M", "InputFormat", "yyyyMMdd");
opts = setvaropts(opts, "Time_M", "InputFormat", "HH:mm:ss.SSSS");
opts = setvaropts(opts, ["Region_name", "Region_class"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Region_name", "Region_class"], "ThousandsSeparator", ",");

% Import the data
school_import = readtable(filename, opts);

end